# docker-compose file

version: '3.3'

services:
  yii:
    restart: always
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      # Re-use local composer cache via host-volume
      - .tmp/composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    expose:
     - 80
    environment:
      PHP_ENABLE_XDEBUG: 1
    depends_on:
      - mysql

  mysql:
    restart: on-failure
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pwd
    ports:
      - 3306:3306

  composer:
    restart: on-failure
    image: yiisoftware/yii2-php:7.4-apache
    command: ["composer", "install"]
    volumes:
      - ./:/app
    depends_on:
      - yii

  init:
    restart: on-failure
    image: yiisoftware/yii2-php:7.4-apache
    command: ["php", "init", "--env=${ENVIRONMENT}","--overwrite=All"]
    volumes:
      - ./:/app
    depends_on:
      - composer

  migrate:
    restart: on-failure
    image: yiisoftware/yii2-php:7.4-apache
    command: ["php", "yii", "migrate/up", "--interactive", "0"]
    volumes:
      - ./:/app
    depends_on:
      - init

  letsencrypt:
    image: certbot/certbot
    command:
      - certonly
      - -d
      - locustv2.com
      - --webroot
      - -w
      - /app/web
      - --agree-tos
      - -m
      - yjoodhisty+locustv2@gmail.com
    volumes:
      - ./:/app
      - .tmp/letsencrypt:/etc/letsencrypt
    depends_on:
      - init

  nginx:
    image: nginx:latest
    depends_on:
      - letsencrypt
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .tmp/letsencrypt:/letsencrypt
