# ssl docker-compose file

version: '3.3'

services:
  yii:
    restart: always
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ./vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 443:443
